config/routes.rb
Rails.application.routes.draw do
  namespace :admin do 
    resources :dashboards
    resources :categories do
      resources :item, controller: '/admin/items' do
        resources :pictures
      end
    end
  end
  map.resources :items do |item|
    item.resources :pictures
  end
  devise_for :users
  root to:"home#index"
  get 'home/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :items
end

app/models/item.rb
class Item < ApplicationRecord
	belongs_to :category
	has_many :pictures, as: :imageable
end

app/models/picture.rb
class Picture < ApplicationRecord
	belongs_to :imageable, polymorphic: true
	mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_one :picture, as: :imageable
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < ApplicationController
  before_action :check_user_type
 def index
    @categories = Category.all
 end
 def new
   @categories = Category.new 
 end
 def create
    @categories = Category.new(category_params)
    if @categories.save
      render 'show'
    else
      redirect_to new_admin_category_path
    end
 end
 def edit
  @categories = Category.find(params[:id])
 end
 def show
  @categories = Category.find(params[:id])
 end
 def update
   @categories = Category.find(params[:id])
    if @categories.update(category_params)
      render 'show'
    else
      redirect_to edit_admin_category_path
    end      
 end
 def destroy
  @categories = Category.find(params[:id])
  @categories.destroy
  redirect_to admin_categories_path
 end

 private
  #permited parameters
  def category_params
    params.require(:category).permit(:name)
  end
  #to check the user type
  def check_user_type
    if current_user.user_type == true    #for admin its false
      redirect_to root_path
    end
  end
end

app/controllers/admin/dashboards_controller.rb
class Admin::DashboardsController < ApplicationController

  def index
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
	def index
		@category = Category.find(params[:category_id])
		@items = @category.items.all
	end
	def new
		@category = Category.find(params[:category_id])
		@item = Item.new
	end
	def create
		@category = Category.find(params[:category_id])
		@item = @category.items.create(item_params)
		@picture = Picture.new
		@image = @picture.image(params[:file])
		byebug
		redirect_to admin_category_item_index_path
	end
	def show
		@category = Category.find(params[:category_id])
		@item = @category.items.find(params[:id])
	end
	def destroy
		@category = Category.find(params[:category_id])
		@item = @category.items.find(params[:id])
		@item.destroy
		redirect_to admin_category_item_index_path
	end
	private
		def item_params
			params.require(:item).permit(:name,:category_id)
		end
end

app/controllers/admin/pictures_controller.rb
class Admin::class PicturesController < ApplicationController
	before_action :local_post
	def index
		@picture = @imageable.pictures.all		
	end
	def new
		@picture = @imageable.pictures.new		
	end
	def create
		@image = @imageable.pictures.new(params.require(:picture).permit(:image))
		if @image.save
			redirect_to post_picture_path(@imageable,@image)
		else
			render 'new'
		end
	end
	def show
		@picture = @imageable.pictures.find(params[:id])

	end
	def destroy
		@picture = @imageable.pictures.find(params[:id])
		@picture.destroy
		redirect_to post_pictures_path
	end
	private
	def local_post
		resources, id = request.path.split('/')[4, 5]
		@imageable = resources.singularize.classify.constantize.find(id)
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def after_sign_in_path_for(resource) 
    if current_user.user_type?
      root_path
    else
      admin_dashboards_path
    end
  end
  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name,:dob,:phone,:email,:password,:password_confirmation,:user_type])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/views/admin/categories/edit.html.erb
<%= form_for @categories, url:admin_category_path(@categories), method: :patch do |cate| %>
  <%= cate.label :Name %>
  <%= cate.text_field :name %>
  <%= cate.submit 'Update'%>
<% end %>

app/views/admin/categories/index.html.erb
<% @categories.each do |cate| %>
	<%= cate.name %>
	<%=	link_to 'show', admin_category_path(cate) %>,
	<%= link_to 'Delete', admin_category_path(cate), method: :delete , data: {confirm: 'Are You Sure'} %>,
	<%= link_to 'Create Item', new_admin_category_item_path(cate) %>,
	<%= link_to 'Show Items', admin_category_item_index_path(cate) %><br/>
<% end %>
<%= link_to 'Create new category', new_admin_category_path %>

app/views/admin/categories/new.html.erb
<%= form_for @categories, url: admin_categories_path do |cate| %>
  <%= cate.label :Name %>
  <%= cate.text_field :name %>
  <%= cate.submit "Create" %>
<% end %>

app/views/admin/categories/show.html.erb
<%= @categories.name %>
<%= link_to 'Edit', edit_admin_category_path(@categories) %>
<br/>
<%= link_to 'Create new category', new_admin_category_path %>

app/views/admin/dashboards/index.html.erb
<h1>Dashboards#index</h1>
<p>Find me in app/views/dashboards/index.html.erb</p>
<%= link_to "Create Category", new_admin_category_path %>,<%= link_to 'Show Category', admin_categories_path %>
<%# link_to "Create Item", new_admin_category_item_path %>

app/views/admin/items/index.html.erb
<h3><%= link_to @category.name, admin_category_path(@category) %></h3><br/>
<%= @items.each do |item| %> 
  <%= item.name %> 
  <%= link_to 'Show', admin_category_item_path(@category,item)%> ,
  <%= link_to 'Delete', admin_category_item_path(@category,item), method: :delete,
              data:{confirm:  "Are You Sure to delete #{item.name.upcase}"} %><br/> 
<% end %><br />
<%= link_to 'Create Item', new_admin_category_item_path(@category) %>

app/views/admin/items/new.html.erb
<%= form_for [@category,@category.items.build], url: admin_category_item_index_path(@category) do |item| %>
  <%= item.label :Name %>
  <%= item.text_field :name %>
  <%= item.label :Image %>
  <%= item.file_field :image%>
  <%= item.submit 'Create Item' %>
<% end %>

app/views/admin/items/show.html.erb
<%= @item.name %>
<%# image_tag @category.image_url.to_s%>
	<%= link_to 'Delete', admin_category_item_path, method: :delete, data:{confirm:  "Are You Sure to delete #{@item.name.upcase}"} %><br />
	<%= link_to 'Create Item', new_admin_category_item_path(@category) %>

app/views/admin/pictures/index.html.erb
<%= @picture.each do |pic| %>
	<%= image_tag pic.image_url.to_s %>
	<%= link_to "Delete",post_picture_path(@imageable,pic), method: :delete, data: {Confirm: "Are You sure"} %>
	<%= link_to "Show", post_picture_path(@imageable,pic) %>
<% end %>

app/views/admin/pictures/new.html.erb
<%= form_for [@imageable, @picture] do |image| %>
	<h3><%= image.label :Image %></h3>
	<%= image.file_field :image%><br/>
	<%= image.submit "Add Image" %>
<% end %>

app/views/admin/pictures/show.html.erb
<%= image_tag @picture.image_url.to_s%>
<%= link_to "Delete",post_picture_path(@imageable,@picture), method: :delete, data: {Confirm: "Are You sure"} %>

app/views/home/index.html.erb
<h1>Home index</h1>
<p>Welcome to Home</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EcommerceNew</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render file: 'navbar' %>
    <%= yield %>
  </body>
</html>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>